### ISSUE TITLE
parseSBMLNotesField assigns a blank SUBSYSTEM to 'Exchange'

### ISSUE THREAD

**Issue by chrismgowen** [opencobra/cobratoolbox#32] opened 2014-12-29 17:55 UTC
In parsing the SBML notes field, this function includes the statement

> if (isempty(subSystem))
>           subSystem = 'Exchange';
>        end

which assigns the SubSystem 'Exchange' to any reaction that has SUBSYSTEM showing up in its notes field but with no subsystem assigned. 

The problem with this is that reading an SBML model without assigned subsystems automatically creates this field in the model structure, and then writing that model again to a new SBML file creates those (empty) fields. The new model will then be read with all reactions being assigned to the subsystem 'Exchange.' This could be fixed by simply removing this block of code, unless there is a compelling reason to keep it.

**Comment by longfeimao** [comment] 2015-01-12 14:16
Hi Chris, Thank you for spotting this. To avoid any potential problems caused by automatically assigning subsystem 'Exchange', at least it might be needed to include some comments beside the codes in "parseSBMLNotesField.m" to make people aware of their functions, or it'd better better to simply remove the codes as you suggested :).

**Comment by laurentheirendt** [comment] 2017-03-14 19:35
@tpfau, may we close this issue?

**Comment by tpfau** [comment] 2017-03-15 07:47
@laurentheirendt, yes, this is no longer in the code since the rework of SBML I/O by @longfeimao

**Comment by laurentheirendt** [comment] 2017-03-15 07:52
Thanks @tpfau ! Closing now.

**Closed by laurentheirendt** 2017-03-15 07:52 UTC
