### ISSUE TITLE
Error trying to use changeCobraSolver- please help!

### ISSUE THREAD

**Issue by Jack-Rutter** [opencobra/cobratoolbox#521] opened 2017-06-07 13:28 UTC
Hi everyone,

I am trying to use the command changeCobraSolver in Matlab (so that I can go on to perform a FBA), I call it using this command:

changeCobraSolver('glpk','LP');

However i keep getting the following error:

Not enough input arguments.

Error in changeCobraSolver (line 209)
        if printLevel > 0 && (strcmpi(solverName, 'gurobi') || strcmpi(solverName, 'ibm_cplex') ||
        strcmpi(solverName, 'tomlab_cplex') || strcmpi(solverName, 'cplex_direct') || strcmpi(solverName,
        'mosek'))

Any help on how to fix this would be really appreciated! Thank you so much.

Best wishes,
Jack

**Comment by laurentheirendt** [comment] 2017-06-07 13:42
@Jack-Rutter, thanks for reporting this. Are you using the latest version of The COBRA Toolbox?

Did you run:
```Matlab
initCobraToolbox
```
With the current version, this error cannot be reproduced. In order to debug, may you provide us with the output of:
```Matlab
generateSystemConfigReport()
```
Actually, you may want to check out [our forum](https://groups.google.com/forum/#!forum/cobra-toolbox) for more immediate support. Thanks.

**Comment by Jack-Rutter** [comment] 2017-06-07 13:47
Thank you for getting back to me so quickly.

I have generated the system configuration report,
[COBRAconfigReport.txt](https://github.com/opencobra/cobratoolbox/files/1058168/COBRAconfigReport.txt)

I hope this helps,

Jack

**Comment by laurentheirendt** [comment] 2017-06-07 15:03
Thank you @Jack-Rutter.

However, based on the report, it looks as if 
```Matlab
changeCobraSolver('glpk', 'LP');
```
works fine. May you try again?

**Comment by laurentheirendt** [comment] 2017-06-07 19:09
Closing, as reported behaviour is irreproducible.

Thanks @Jack-Rutter! Feel free to post in the [forum](https://groups.google.com/forum/#!forum/cobra-toolbox) should you run into any other issues!

**Comment by pavaoa** [comment] 2017-06-08 13:19
My apologies for reviving a "closed" issue.

I encountered this issue as well. The problem is that changeCobraSolver(), in addition to taking solverName and solverType as arguments, also takes the "optional" argument printLevel, which determines whether or not warnings and errors are silenced. The default value for printLevel should be 1, and changeCobraSolver() sets this value at line 235 if printLevel is not given by the user as an argument:
```
if nargin < 3
    printLevel = 1;
end
```
However, printLevel is used in line 209 of changeCobraSolver() before its default value is set at line 235. As such, if printLevel is not provided as an argument, there will be an error because printLevel is not initialized. Hence, "not enough input arguments" is the error message. Effectively, the printLevel argument is not really optional because it is only initialized after it is called in the case where the user does not provide it as an argument.

Two solutions:

1. Provide the printLevel argument each time you call changeCobraSolver(). This ensures that printLevel is initialized each time. The following should work:
`changeCobraSolver('glpk','LP',1);`

2. Modify changeCobraSolver() so that printLevel is initialized before it is first used, even if it is not provided as an argument. That would entail moving 
```
if nargin < 3
    printLevel = 1;
end
```
earlier in changeCobraSolver.m. Moving it around line 148 worked for me.

Hope this helps.

Aidan

**Comment by laurentheirendt** [comment] 2017-06-08 13:26
Thanks @pavaoa for reporting this. Maybe that was the issue then that @Jack-Rutter experienced.

May you submit a contribution (pull-request) using the [MATLAB.devTools](https://github.com/opencobra/MATLAB.devTools) by moving
```Matlab
if nargin < 3
    printLevel = 1;
end
```
to line 148? That would help a lot! Thanks!

**Comment by laurentheirendt** [comment] 2017-06-08 18:50
Fixed by PR #528. Thanks!

**Closed by laurentheirendt** 2017-06-08 18:50 UTC
Labels: beginner, bug

**Comment by Jack-Rutter** [comment] 2017-06-26 15:09
Hi Everyone!

I am working on adapting the FBA model for E coli. As part of my model I want to change the carbon sources the cells are using.

Is there a way to change the carbon source for a subset of reactions within the model?

From what I have read around the subject, the toolbox lets you choose from 13 different carbon sources; however, I am hoping to use Lysine as a carbon source for the reactions.

Is it possible to manually set a specific carbon source for a subset of reactions and then specify the levels of this carbon source available to the model?

Is there a way to incorporate this into the model? And if so, are there any tutorials/papers/articles that I can read through to help implement the changes I need please?

Thank you for your help.
Best wishes,
Jack

**Comment by laurentheirendt** [comment] 2017-06-27 02:04
@Jack-Rutter, thanks for posting here. However, you might want to check out the [COBRA forum](https://groups.google.com/forum/#!forum/cobra-toolbox) and post your question there. Thanks.
