### ISSUE TITLE
initCobraToolbox not functioning on CentOS

### ISSUE THREAD

**Issue by ScarabMonkey** [opencobra/cobratoolbox#1244] opened 2018-06-07 16:30 UTC
InitCobraToolbox seems to run a whole bunch of git commands - unfortunately some of the syntax used appears to be invalid on the git version shipped with both CentOS 7 and 6 (i.e. Git 1.8).

**I hereby confirm that I have:**

- [X] Tried to solve the issue on my own
- [X] Retried to run my code with the latest version of The COBRA Toolbox
- [X] Checked that a similar issue has not already been opened

-------------------------------
Error message:
-------------------------------
````
software@omega[~/matlab/toolboxes/cobratoolbox]% matlab
MATLAB is selecting SOFTWARE OPENGL rendering.

                                                                   < M A T L A B (R) >
                                                         Copyright 1984-2017 The MathWorks, Inc.
                                                         R2017a (9.2.0.556344) 64-bit (glnxa64)
                                                                     March 27, 2017

 
To get started, type one of these: helpwin, helpdesk, or demo.
For product information, visit www.mathworks.com.
 
>> initCobraToolbox


      _____   _____   _____   _____     _____     |
     /  ___| /  _  \ |  _  \ |  _  \   / ___ \    |   COnstraint-Based Reconstruction and Analysis
     | |     | | | | | |_| | | |_| |  | |___| |   |   The COBRA Toolbox - 2018
     | |     | | | | |  _  { |  _  /  |  ___  |   |
     | |___  | |_| | | |_| | | | \ \  | |   | |   |   Documentation:
     \_____| \_____/ |_____/ |_|  \_\ |_|   |_|   |   http://opencobra.github.io/cobratoolbox
                                                  | 

 > Checking if git is installed ...  Done.
 > Checking if the repository is tracked using git ...  Done.
 > Checking if curl is installed ...  Done.
 > Checking if remote can be reached ...  Done.
 > Initializing and updating submodules (this may take a while)...usage: git submodule [--quiet] add [-b <branch>] [-f|--force] [--name <name>] [--reference <repository>] [--] <repository> [<path>]
   or: git submodule [--quiet] status [--cached] [--recursive] [--] [<path>...]
   or: git submodule [--quiet] init [--] [<path>...]
   or: git submodule [--quiet] deinit [-f|--force] [--] <path>...
   or: git submodule [--quiet] update [--init] [--remote] [-N|--no-fetch] [-f|--force] [--rebase] [--reference <repository>] [--merge] [--recursive] [--] [<path>...]
   or: git submodule [--quiet] summary [--cached|--files] [--summary-limit <n>] [commit] [--] [<path>...]
   or: git submodule [--quiet] foreach [--recursive] <command>
   or: git submodule [--quiet] sync [--recursive] [--] [<path>...]
Error using initCobraToolbox (line 196)
The submodules could not be initialized.
 
>> exit
software@omega[~/matlab/toolboxes/cobratoolbox]% git --version
git version 1.8.3.1
software@omega[~/matlab/toolboxes/cobratoolbox]% lsb_release -d
Description:	CentOS release 6.9 (Final)
````

**Comment by laurentheirendt** [comment] 2018-06-07 16:41
We officially support neither `CentOS`, nor `MATLAB R2017a`, but may you try using Linuxbrew (http://linuxbrew.sh/)? There you can then use another version of `git` other than the one shipped by CentOS.

**Comment by ScarabMonkey** [comment] 2018-06-07 16:44
Okay, where can I find the list of supported OS's and Matlab versions?

**Comment by laurentheirendt** [comment] 2018-06-07 16:57
In general, the `a` versions of MATLAB *should* work, but are not officially supported (i.e the COBRA Toolbox is not explicitly tested with `a` versions, apart from the solvers). Hence, we refer to using the `b`version instead.

Actually, your version of MATLAB is not the root cause of this issue, but the version of `git`. Did you try using Linuxbrew?

**Comment by laurentheirendt** [comment] 2018-06-07 17:12
If it doesn't work by installing `git` via Linuxbrew, may you help us looking into this issue? We are actually looking for motivated people to help us make the COBRA Toolbox compatible on more versions of Linux. 

You are more than welcome to contribute 👍 🎉

**Comment by akaviaLab** [comment] 2018-06-07 19:01
AFAIK CentOS is usually used on servers.
Most servers have some kind of system for loading extra software. The cluster I use uses the module system (http://modules.sourceforge.net/man/module.html), and requires loading git manually (using "module load git") to get a newer version. Does your server have something similar? If so, can you try loading git and see if you get a newer version, and if initCobraToolbox works?

**Comment by laurentheirendt** [comment] 2018-06-11 16:07
@ScarabMonkey, any news?

**Comment by ScarabMonkey** [comment] 2018-06-12 09:11
I'm taking a look at the source and the first thing is that old git doesn't accept "--depth" for "submodule update"...
trying now without that ...

**Comment by akaviaLab** [comment] 2018-06-12 10:04
Have you tried loading a git module? This is exactly the problem I had on my CentOS cluster.

**Comment by laurentheirendt** [comment] 2018-06-21 05:44
@ScarabMonkey, how did that work out?

**Comment by laurentheirendt** [comment] 2018-06-22 07:18
Great! Would you mind submitting a pull request with a version check on `git`?

I would recommend however to update your git version. You are using version 1.8.3, which dates back to June 2013 (https://github.com/git/git/releases/tag/v1.8.3.1).

**Comment by laurentheirendt** [comment] 2018-06-26 14:17
@ScarabMonkey, will you submit a PR? Otherwise, I think we can close this issue.

**Comment by laurentheirendt** [comment] 2018-06-27 05:21
PR open - closing here.

**Closed by laurentheirendt** 2018-06-27 05:21 UTC
