### ISSUE TITLE
problem with [missingMets,presentMets] = biomassPrecursorCheck(model)

### ISSUE THREAD

**Issue by Sunweikang** [opencobra/cobratoolbox#1355] opened 2018-10-13 02:03 UTC
when I finished my rough model , I add the biomass reaction and then run the code '[missingMets,presentMets] = biomassPrecursorCheck(model)' in matlab. TWO problems  occurred  ：
 
1. Undefined function or variable 'presentMets' 
2. Undefined operator '*' for input arguments of type 'struct'
I have changeCobraSolver already and i really cannot fix it . 
Anyone can help, Please ！

**Comment by laurentheirendt** [comment] 2018-10-14 16:35
Duplicate of forum issue: https://groups.google.com/forum/#!topic/cobra-toolbox/26KH_hwsgOM

**Closed by laurentheirendt** 2018-10-14 16:35 UTC
